export const RESPONSE_CODES = {
    INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
    EMAIL_ALREADY_EXISTS: "EMAIL_ALREADY_EXISTS",
    VALIDATION_ERROR: "VALIDATION_ERROR",
    RESOURCE_CONFLICT: "RESOURCE_CONFLICT",
    INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
    TOKEN_EXPIRED: "TOKEN_EXPIRED",
    INVALID_TOKEN: "INVALID_TOKEN",
    VALIDATION_FAILED: "VALIDATION_FAILED",
} as const;

export type ResponseCode = (typeof RESPONSE_CODES)[keyof typeof RESPONSE_CODES];
